name: GitHub Actions Pandoc - PDF
#on: [push] # be careful, don't get in a commit-loop :D
on: [workflow_dispatch]
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Get files
        uses: actions/checkout@v2
          
      - name: Load pandoc
        uses: docker://pandoc/latex:2.9
        with:
          args: >-  # allows you to break string into multiple lines
            --bibliography oxygen.bib
            -V geometry="margin=2cm"
            --output=oceangliders_oxygen_sop_v0.pdf
            oxygen.md
          
      - name: Commit file
        run: |
          git config --global user.name 'Github actions bot'
          git config --global user.email ''
          git add oceangliders_oxygen_sop_v0.pdf
          git commit -m "automated pandoc build"
          git push
